language: python
python:
 - 2.6
 - 2.7
 - 3.2
 - 3.3
install:
 - python setup.py -q develop
 - pip install pytest pytest-cov coveralls
 # Install unittest2 on 2.6
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
script: 
    py.test --cov skosprovider_oe --cov-report term-missing skosprovider_oe/tests
after_success:
    coveralls
